### ISSUE TITLE
ErrorException when removing empty /tmp directory on Heroku

### ISSUE THREAD

**Issue by eabay** [spatie/image#38]
Thanks for this great library! We are using it via spatie/laravel-medialibrary package.

https://github.com/spatie/image/blob/d868b79d451046877c225af92a40114734eb4e5a/src/GlideConversion.php#L107

This line tries to remove `/tmp` directory on Heroku and throw the Exception:

```
ErrorException: rmdir(/tmp): Read-only file system in /app/vendor/spatie/image/src/GlideConversion.php:107
Stack trace:
#0 /app/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'rmdir(/tmp): Re...', '/app/vendor/spa...', 107, Array)
#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'rmdir(/tmp): Re...', '/app/vendor/spa...', 107, Array)
#2 /app/vendor/spatie/image/src/GlideConversion.php(107): rmdir('/tmp')
#3 /app/vendor/spatie/image/src/Image.php(111): Spatie\Image\GlideConversion->save('/app/storage/me...')
#4 /app/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(101): Spatie\Image\Image->save()
#5 /app/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(68): Spatie\MediaLibrary\FileManipulator->performConversion(Object(App\Modules\MediaLibrary\Media), Object(Spatie\MediaLibrary\Conversion\Conversion), '/app/storage/me...')
#6 /app/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(32): Spatie\MediaLibrary\FileManipulator->performConversions(Object(Spatie\MediaLibrary\Conversion\ConversionCollection), Object(App\Modules\MediaLibrary\Media))
#7 [internal function]: Spatie\MediaLibrary\Jobs\PerformConversions->handle()
#8 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#13 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#14 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Spatie\MediaLibrary\Jobs\PerformConversions))
#15 /app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): Illuminate\Bus\Dispatcher->dispatchNow(Object(Spatie\MediaLibrary\Jobs\PerformConversions), false)
#17 /app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(69): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#18 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(317): Illuminate\Queue\Jobs\Job->fire()
#19 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(267): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#20 /app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(113): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#21 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'media:generate', Object(Illuminate\Queue\WorkerOptions))
#22 /app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'media:generate')
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#24 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#29 /app/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#30 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /app/vendor/symfony/console/Application.php(936): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /app/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /app/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 {main}
```

What do you think about silencing the error with `@` as a workaround?

#31 might also be related to this issue.

**Comment by freekmurze** [comment]
I recently made some improvements around the usage of the `tmp` directory. Are you using the latest version?

Silencing errors is, for our stuff, in most cases not the way to go.

**Comment by eabay** [comment]
I know it's not the best practice, just need to know your opinion. It's the fastest solution for me without making too much investment right now 😁

medialibrary requires 1.4, so it should be the latest if you do not mean master as the latest version.

What would you think about the right solution, making it configurable or...?

**Comment by dbpolito** [comment]
I'm having this problem too on my local docker env (using `vessel`). I don't think we should delete the server `/tmp` folder, even if it's empty.

**Comment by dbpolito** [comment]
@freekmurze This is bugging me a lot 😢 , my current around is running `touch /tmp/.keep` on my container.

I can totally open a PR for this if you point me the way you want to handle it, options:

1. Simply don't remove the folder (my preference)
2. Check if it's `/tmp`, if so, don't remove
3. try / catch
4. error suppression

**Comment by freekmurze** [comment]
I'd probably go for nr. 1, but we should make sure that people's hard drives are not filled up with temporary images.

**Comment by brendt** [comment]
I want to fix this this week. I personally don't agree on the solution to never remove the folders. This would fill the directory with unneeded folders. I think there's a real issue for long running servers.

I'd suggest the following solution: https://github.com/spatie/image/pull/45

**Comment by ammonkc** [comment]
@brendt I don't think the directory filling up with old files will be a problem. The converted files are deleted on line 104. There is no reason to ever try to delete the `/tmp` directory because it's a system folder. 

https://github.com/spatie/image/blob/2ff09d9eafbeccc71f29ee7a9eb6169a856df75e/src/GlideConversion.php#L104

Here are 2 possible solutions:

1. Simply don't try to remove the folder at all. 
2. create the conversion files inside a sub directory of `/tmp`. something like `/tmp/glide_conversions`:
```php
// line 50
$conversionDir = 'glide_conversions';
$this->conversionResult = sys_get_temp_dir().DIRECTORY_SEPARATOR.$conversionDir.DIRECTORY_SEPARATOR.$glideServer->makeImage(
                    pathinfo($inputFile, PATHINFO_BASENAME),
                    $this->prepareManipulations($manipulationGroup)
                );
```

**Comment by ammonkc** [comment]
After much digging I've found the cause of this issue. 

It's related to something called "systemd /tmp isolation". The php service (and others like httpd) have the PrivateTmp option to true in the systemd script (/usr/lib/systemd/system).

It's a security measure where a new /tmp is created and isolated from the other ones. All the data saved inside are deleted once the service is stopped.

If running on a Linux system where systemd has PrivateTmp=true (which is the default on CentOS 7 and perhaps other newer distros), sys_get_temp_dir() function will simply return "/tmp", not the true, much longer, somewhat dynamic path. 
(example: `systemd-private-5049768e046a4449b2d8dd552949bb17-php-fpm.service-FYJIWf/tmp/` )
see: [http://php.net/manual/en/function.sys-get-temp-dir.php#121073](url)

as a quick fix you can disable the PrivateTmp option. see [https://gryzli.info/2015/06/21/centos-7-missing-phpapache-temporary-files-in-tmp-systemd-private-temp/](url).
But since this is a security feature of linux, a better long term solution would be to avoid using the system /tmp directory to cache conversion files, and instead use a directory within the project.
